# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "deploying to dev"
  
  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo "deploying to test"
      - run: |
          echo "doing some tests"
          sleep 5
      
  deploy-prod:
    runs-on: ubuntu-latest
    needs: ["deploy-test","deploy-dev"]
    environment: prod
    steps:
      - run: echo "deploying to prod"
    
