# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  push: {}
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Make a comment
        if: context.issue.number
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "Hello, this message was sent by GitHub Actions!"
            });
          

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
    outputs:
      name: test
      options.loadBalancer.enabled: "true"
      options.loadBalancer.public: "true"
      
  useOutputs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs['options.loadBalancer.enabled'] }}
